### ISSUE TITLE
作者你好，我最近在研究LLVM To JS ，希望能活得帮助，谢谢。 

### ISSUE THREAD

**Issue by sunweiliang** [notcome/SweetJS#1]
Email:weiliang.soon@gmail.com

**Comment by notcome** [comment]
首先，这个项目因为时间不足已经停了。其次，LLVM 翻译到 JavaScript 有现成的[解决方案](https://github.com/kripken/emscripten)。最后，Swift 翻译到 JavaScript 和 LLVM 生成的中间代码翻译过去有很大差距，前者会保留很多语义，后者的话很多信息都会丢失，比如说循环可能被展开，无用代码可能被消去，等等。得到的 JavaScript 代码会和源代码差距巨大。
